
const PASSWORD_MIN_LENGTH = 4;
const PASSWORD_SALT = 10;
const JWT_SECRET_KEY = 'JWT_SECRET_KEY_KOA';
const JWT_EXPIRY_HOURS = '24h';

module.exports = {
    PASSWORD_MIN_LENGTH,
    PASSWORD_SALT,
    JWT_SECRET_KEY,
    JWT_EXPIRY_HOURS
}